//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversorTemasCMS.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConversorTemasCMS.Recursos.ConversorResource", typeof(ConversorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        internal static string BtnExaminar {
            get {
                return ResourceManager.GetString("BtnExaminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la ruta de destino.
        /// </summary>
        internal static string BtnExaminarError {
            get {
                return ResourceManager.GetString("BtnExaminarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de destino del archivo resultante: .
        /// </summary>
        internal static string BtnExaminarExito {
            get {
                return ResourceManager.GetString("BtnExaminarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Fichero (.Html).
        /// </summary>
        internal static string BtnFicheroHtml {
            get {
                return ResourceManager.GetString("BtnFicheroHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar el archivo Html.
        /// </summary>
        internal static string BtnFicheroHtmlError {
            get {
                return ResourceManager.GetString("BtnFicheroHtmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo Html cargado correctamente.
        /// </summary>
        internal static string BtnFicheroHtmlExito {
            get {
                return ResourceManager.GetString("BtnFicheroHtmlExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Fichero (.Xml).
        /// </summary>
        internal static string BtnFicheroXml {
            get {
                return ResourceManager.GetString("BtnFicheroXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar el archivo Xml.
        /// </summary>
        internal static string BtnFicheroXmlError {
            get {
                return ResourceManager.GetString("BtnFicheroXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo Xml cargado correctamente.
        /// </summary>
        internal static string BtnFicheroXmlExito {
            get {
                return ResourceManager.GetString("BtnFicheroXmlExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar un fichero de destino.
        /// </summary>
        internal static string BtnGenerarDestinolInfo {
            get {
                return ResourceManager.GetString("BtnGenerarDestinolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar un archivo .Html.
        /// </summary>
        internal static string BtnGenerarHtmlInfo {
            get {
                return ResourceManager.GetString("BtnGenerarHtmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar tema.
        /// </summary>
        internal static string BtnGenerarTema {
            get {
                return ResourceManager.GetString("BtnGenerarTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema generado con éxito.
        /// </summary>
        internal static string BtnGenerarTemaExito {
            get {
                return ResourceManager.GetString("BtnGenerarTemaExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario seleccionar un archivo .Xml.
        /// </summary>
        internal static string BtnGenerarXmlInfo {
            get {
                return ResourceManager.GetString("BtnGenerarXmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        internal static string LblIdioma {
            get {
                return ResourceManager.GetString("LblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversor de temas para Drupal.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
